### ISSUE TITLE
C Program to shutdown Windows

### ISSUE THREAD

**Issue by rishabh1911007** [DSC-Galgotias/Hacktoberfest2022#123]
Could you please assign me for this issue.

**Comment by rishabh1911007** [comment]
#Hacktoberfest2022

**Comment by theDeviser** [comment]
@rishabh1911007 @Rishi-srk @SarthakDeshmukh13 sorry this won't be accepted under hacktoberfest in this repository, maybe you can refer to another repository that accepts C Programs
