### ISSUE TITLE
Balloon popping game using html-css-js

### ISSUE THREAD

**Issue by Vamps1975** [DSC-Galgotias/Hacktoberfest2022#139]
Hey, 
I wanted to add a Simple Balloon Popping game made using html-css-js
It doesn't have that much functionality
I'm a first-time contributor I hope you assign this to me 
Thank You

**Comment by theDeviser** [comment]
Yes you can contribute in this project and it will be accepted under Hacktoberfest after a review. The only sort of contributions we don't accept are DSA and interview problem codes.
