### ISSUE TITLE
Receive Form Data on Email

### ISSUE THREAD

**Issue by Gaurika-Gupta** [DSC-Galgotias/Hacktoberfest2022#183]
Working Web Application where Form data filled is sent to our email address.

**Comment by Gaurika-Gupta** [comment]
Please assign me the issue under Hacktoberfest 2022. It is a very useful functionality.

**Comment by theDeviser** [comment]
the issue has been assigned to @Gaurika-Gupta. Don't forget to add a readme.md in your project's folder.
