### ISSUE TITLE
Add live weather telling app

### ISSUE THREAD

**Issue by AbhishekKumar2002** [DSC-Galgotias/Hacktoberfest2022#86]
I want to add a live weather telling web page which will tell about the live weather of the place you search. Please assign me under Hacktoberfest

**Comment by theDeviser** [comment]
a similar project exists in our repository so maybe you can try to add some features to our project. It will be considered valid under hacktoberfest.

**Comment by theDeviser** [comment]
the issue has been closed due to the contributor's inactivity
